[package]
name = "nicehash-cpumulti-miner-optimiser"
version = "0.1.0"
authors = ["Stefano Chiodino <louderth@gmail.com>"]

[dependencies]
clap = {version = "2.26.2", features = ["yaml"]}
regex = "0.2"
lazy_static = "0.2.9"
reqwest = "0.8.0"